language: php

php:
    - 7.1
    - 7.2
    - 7.3
    - nightly

matrix:
    fast_finish: true
    include:
        - php: 7.1
          env: COMPOSER_FLAGS="--prefer-lowest"
        - php: 7.1
          env: COMPOSER_FLAGS="--prefer-stable"
    allow_failures:
        - php: nightly

install:
    - composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
    - vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
    - if [ "$TRAVIS_PHP_VERSION" != "nightly" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
    - if [ "$TRAVIS_PHP_VERSION" != "nightly" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
